pipeline_config:
  development: True 
  reporting: True

datasets: 

  ds-11:
    name: ds-11

  ds-21:
    name: ds-21
  # ds-11_api_added:
  #   name: ds-11_api_added

  # ds-21_api_added:
  #   name: ds-21_api_added